a(variable)에 1(content)을 넣어라
variable types

In [3]:
a = 1; print(type(a))

<class 'int'>


int -->  정수를 뜻함

In [2]:
a

1

In [5]:
print(a)

1


; -> output으로 2만 도출

In [8]:
a=1;b=2

In [10]:
a
b

2

In [11]:
print(a)
print(b)

1
2


a int로 설정, 따라서 print a -> 1 

In [12]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [13]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [14]:
print(a)

1


''의 역할 = contents가 text임을 뜻함

* str = string
a[1] : 두번째 글자 지정. 
--> [-1] 은 맨 마지막 글자를 지정

In [15]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [16]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


 [ , ] --> list 작성 (contents의 나열, 요소 순서 관리)

cf. Tuple (튜플) 차이점 1)  (,) 로 표기 2) 데이터값 생성/삭제/수정 X 

In [17]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [18]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


DIct -> 하나의 Pair 설정 / print(a["a"]) : a 중에 "a"의 내용을 도출해라

In [20]:
a[-1][0]

3

In [21]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [22]:
a=['apple','banana']

In [23]:
a[0]

'apple'

파이썬에서는 행렬을 자동 실행하는 툴이 없어서 Numpy 사용

In [24]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [25]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [26]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


* Matrix 함수 --> 기존 값을 행렬로 변경 
* Class --> 특정 Function을 특정 Variables와 Packaging 한 것
: 파이선의 기본 요소 = 1) Function 2) variable 3) syntax

In [27]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [28]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [29]:
c*c.T

matrix([[14, 19],
        [19, 73]])